apiVersion: v1
kind: Service
metadata:
  name: learn-docker-notebook
  labels:
    app: learn-docker
spec:
  ports:
  - name: notebook
    port: 8888
    protocol: TCP
    nodePort: 30888
  - name: http
    port: 30080
    protocol: TCP
    nodePort: 30080
  selector:
    app: learn-docker
  type: NodePort
