apiVersion: v1
kind: Service
metadata:
  name: learn-docker-notebook
  labels:
    app: learn-docker
spec:
  ports:
  - port: 8888
    protocol: TCP
    nodePort: 30888
  selector:
    app: learn-docker
  type: NodePort
